In [1]:
#importin common libraries
from our_eda import *
from our_modeling import *
from our_preprocessing import *

import matplotlib.pyplot as plt
from wordcloud import WordCloud
import numpy as np 
import pandas as pd 
from our_feature_extraction import basic_bag, tf_idf, ClassAwareVectorizer

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/santiagoromero/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/santiagoromero/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/santiagoromero/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/santiagoromero/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/santiagoromero/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/santiagoromero/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]     

## Download dataset files from HuggingFace

### BESSTIE-reddit-sentiment-uk/

In [ ]:
import pandas as pd

splits = {'train': 'reddit-sentiment-uk-train.jsonl', 'validation': 'reddit-sentiment-uk-valid.jsonl'}
df_reddit_sentiment_uk = pd.read_json("hf://datasets/mindhunter23/BESSTIE-reddit-sentiment-uk/" + splits["train"], lines=True)
df_reddit_sentiment_uk_val = pd.read_json("hf://datasets/mindhunter23/BESSTIE-reddit-sentiment-uk/" + splits["validation"], lines=True)
df_reddit_sentiment_uk

In [ ]:
class_distribution(df_reddit_sentiment_uk) # Imbalanced data 

### BESSTIE-reddit-sentiment-au/

In [ ]:
import pandas as pd

splits = {'train': 'reddit-sentiment-au-train.jsonl', 'validation': 'reddit-sentiment-au-valid.jsonl'}
df_reddit_sentiment_au = pd.read_json("hf://datasets/mindhunter23/BESSTIE-reddit-sentiment-au/" + splits["train"], lines=True)
df_reddit_sentiment_au_val = pd.read_json("hf://datasets/mindhunter23/BESSTIE-reddit-sentiment-au/" + splits["validation"], lines=True)
df_reddit_sentiment_au

In [ ]:
class_distribution(df_reddit_sentiment_au)

### BESSTIE-google-sentiment-uk

In [ ]:
import pandas as pd

splits = {'train': 'google-sentiment-uk-train.jsonl', 'validation': 'google-sentiment-uk-valid.jsonl'}
df_google_sentiment_uk = pd.read_json("hf://datasets/mindhunter23/BESSTIE-google-sentiment-uk/" + splits["train"], lines=True)
df_google_sentiment_uk_val = pd.read_json("hf://datasets/mindhunter23/BESSTIE-google-sentiment-uk/" + splits["validation"], lines=True)
df_google_sentiment_uk

In [ ]:
class_distribution(df_google_sentiment_uk)

### BESSTIE-google-sentiment-au

In [ ]:
import pandas as pd

splits = {'train': 'data/google-sentiment-au-train.jsonl', 'validation': 'data/google-sentiment-au-valid.jsonl'}
df_google_sentiment_au = pd.read_json("hf://datasets/mindhunter23/BESSTIE-google-sentiment-au/" + splits["train"], lines=True)
df_google_sentiment_au_val = pd.read_json("hf://datasets/mindhunter23/BESSTIE-google-sentiment-au/" + splits["validation"], lines=True)
df_google_sentiment_au

In [ ]:
class_distribution(df_google_sentiment_au)

### BESSTIE-reddit-sentiment-in

In [ ]:
import pandas as pd

splits = {'train': 'reddit-sentiment-in-train.jsonl', 'validation': 'reddit-sentiment-in-valid.jsonl'}
df_reddit_sentiment_in = pd.read_json("hf://datasets/mindhunter23/BESSTIE-reddit-sentiment-in/" + splits["train"], lines=True)
df_reddit_sentiment_in_val = pd.read_json("hf://datasets/mindhunter23/BESSTIE-reddit-sentiment-in/" + splits["validation"], lines=True)
df_reddit_sentiment_in

In [ ]:
class_distribution(df_reddit_sentiment_in)

### BESSTIE-google-sentiment-in

In [ ]:
import pandas as pd

splits = {'train': 'google-sentiment-in-train.jsonl', 'validation': 'google-sentiment-in-valid.jsonl'}
df_google_sentiment_in = pd.read_json("hf://datasets/mindhunter23/BESSTIE-google-sentiment-in/" + splits["train"], lines=True)
df_google_sentiment_in_val = pd.read_json("hf://datasets/mindhunter23/BESSTIE-google-sentiment-in/" + splits["validation"], lines=True)
df_google_sentiment_in

In [ ]:
class_distribution(df_google_sentiment_in)

## EDA

In [ ]:
combined_sentiment_df = pd.read_csv("data_sentiment_preprocessed.csv")
combined_sentiment_df_val = pd.read_csv("data_sentiment_preprocessed_val.csv")

# Display the combined DataFrame
print(combined_sentiment_df.head())
print(f"Total rows in combined dataset: {len(combined_sentiment_df)}")

In [ ]:
class_distribution(combined_sentiment_df)

#### Number of characters per review

In [ ]:
plt.xlabel('Char Count')
plt.ylabel('Sample Count')
combined_sentiment_df['text'].str.len().hist()

In [ ]:
fig,(ax1,ax2)=plt.subplots(1,2,figsize=(12,8))
ax1.hist(combined_sentiment_df[combined_sentiment_df['sentiment_label']==1]['text'].str.len())
ax1.set_title( 'Positive Reviews')
ax1.set_xlabel('Char Count')
ax2.hist(combined_sentiment_df[combined_sentiment_df['sentiment_label']==0]['text'].str.len())
ax2.set_title( 'Negative Reviews')
ax2.set_xlabel('Char Count')

#### Most common words

In [ ]:
# POSITIVE SENTIMENT
text = " ".join(i for i in combined_sentiment_df[combined_sentiment_df['sentiment_label']==1]['text'])
wordcloud = WordCloud( background_color="white").generate(text)

plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('wordcloud for positive review')
plt.show()


In [ ]:
# NEGATIVE SENTIMENT
text = " ".join(i for i in combined_sentiment_df[combined_sentiment_df['sentiment_label']==0]['text'])
wordcloud = WordCloud( background_color="white").generate(text)

plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('wordcloud for negative review')
plt.show()


## Preprocessing

### Dataset transformation

#### Training dataset

In [ ]:
## Text processing
combined_sentiment_df['clean_text']= combined_sentiment_df['text'].apply(lambda x: text_preprocess(x, remove_stopwords=True, remove_digits=True, stemmer=Stemmer.WordNet))
combined_sentiment_df

In [ ]:
#tokenization
combined_sentiment_df['tokenized_text'] = combined_sentiment_df['clean_text'].apply(lambda x: word_tokenize(x))
combined_sentiment_df

In [ ]:
combined_sentiment_df.to_csv('data_sentiment_preprocessed.csv', index=False)

#### validation dataset

In [ ]:
## Text processing
combined_sentiment_df_val['clean_text']= combined_sentiment_df_val['text'].apply(lambda x: text_preprocess(x, remove_stopwords=True, remove_digits=True, stemmer=Stemmer.WordNet))
combined_sentiment_df_val

In [ ]:
#tokenization
combined_sentiment_df_val['tokenized_text'] = combined_sentiment_df_val['clean_text'].apply(lambda x: word_tokenize(x))
combined_sentiment_df_val

In [ ]:
combined_sentiment_df_val.to_csv('data_sentiment_preprocessed_val.csv', index=False)

## Feature extraction

In [2]:
combined_sentiment_df = pd.read_csv("data_sentiment_preprocessed.csv")
combined_sentiment_df_val = pd.read_csv("data_sentiment_preprocessed_val.csv")

from our_feature_extraction import basic_bag, tf_idf
# Split the data
X_train = combined_sentiment_df.tokenized_text
y_train = combined_sentiment_df.sentiment_label
X_val = combined_sentiment_df_val.tokenized_text
y_val = combined_sentiment_df_val.sentiment_label


### Count BoW 

In [3]:
word_counts, vocab, selected_words, vectorizer, X_train_vec, X_val_vec = basic_bag(X_train, X_val, min_refs=3, debug=True)

Shape (X_train_vec) before reduction:  (8866, 13942)
Shape (X_train_vec) after reuction:  (8866, 6231)
Shape (X_val_vec):  (1212, 6231)


In [4]:
# 10 most common words
word_counts = np.asarray(X_train_vec.sum(axis=0)).flatten()
vocab = np.array(vectorizer.get_feature_names_out())

top_indices = np.argsort(word_counts)[::-1]
top_words = vocab[top_indices[:10]]
top_counts = word_counts[top_indices[:10]]

print('Most common words:')
for word, count in zip(top_words, top_counts):
    print(f"{word}: {count}")

Most common words:
not: 4523
good: 3415
food: 2608
get: 1843
go: 1610
place: 1569
like: 1549
would: 1527
time: 1374
one: 1363


In [5]:
np.unique(X_train_vec[2].toarray())

array([0, 1, 2])

### 1-hot vectors BoW

In [6]:
word_counts, vocab, selected_words, vectorizer, X_train_hot, X_val_hot = basic_bag(X_train, X_val, ohe=True)
print('Shape (X_train_hot): ', X_train_hot.shape)
# Transforming X_val data
print('Shape (X_val_hot): ', X_val_hot.shape)

Shape (X_train_hot):  (8866, 13942)
Shape (X_val_hot):  (1212, 13942)


In [7]:
# Checking if dataset is binary
unique = np.unique(X_train_hot.toarray())
print('Unique values:', unique)

Unique values: [0 1]


### TF-IDF

In [8]:
word_counts, vocab, selected_words, vectorizer, X_train_vec_tf, X_val_vec_tf = tf_idf(X_train, X_val, debug=True)

Shape (X_train_vec) before reduction:  (8866, 13942)
Shape (X_val_vec):  (1212, 13942)


In [9]:
word_counts

array([0.13627029, 0.30674865, 0.54615593, ..., 0.18706859, 0.0743741 ,
       0.26505371])

### N-grams

#### Bigrams

In [10]:
word_counts, vocab, selected_words, vectorizer, X_train_vec_bi, X_val_vec_bi = basic_bag(X_train, X_val, ngram_range=(2,2), min_refs=3, debug=True)

Shape (X_train_vec) before reduction:  (8866, 161809)
Shape (X_train_vec) after reuction:  (8866, 9566)
Shape (X_val_vec):  (1212, 9566)


In [11]:
bigram_vocab = vectorizer.get_feature_names_out()
bigram_counts = np.asarray(X_train_vec_bi.sum(axis=0)).flatten()

bigram_freq = list(zip(bigram_vocab, bigram_counts))

# Soritng
sorted_bigram_freq = sorted(bigram_freq, key=lambda x: x[1], reverse=True)

print("10 most common bigrams:")
for bigram, count in sorted_bigram_freq[:10]:
    print(f"{bigram}: {count}")

10 most common bigrams:
ability work: 0
able eat: 0
able find: 0
able get: 0
able order: 0
absence also: 0
absence clean: 0
absence could: 0
absence fine: 0
absence food: 0


### Embeddings

In [12]:
import gensim.downloader as api

api.info() # List models or just go to the git as it is easier to read there: https://github.com/piskvorky/gensim-data?tab=readme-ov-file
model = api.load("glove-twitter-25") 
model.most_similar("n't")

/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


[('think', 0.9858008027076721),
 ('know', 0.9772163033485413),
 ('but', 0.9746254682540894),
 ('either', 0.9740143418312073),
 ('if', 0.9736496806144714),
 ('they', 0.9727024435997009),
 ('that', 0.9722444415092468),
 ('when', 0.9720438122749329),
 ('would', 0.9706029891967773),
 ('really', 0.9704276323318481)]

In [13]:
model.most_similar('penis')

# Need to check, but I think if we use pretrained embeddings we need to match the preprocessing step to how the embeddings was done

[('vagina', 0.8970811367034912),
 ('finger', 0.8911336064338684),
 ('tongue', 0.8618690371513367),
 ('eye', 0.8475320935249329),
 ('anus', 0.8450093865394592),
 ('eyeliner', 0.8437599539756775),
 ('teeth', 0.8422453999519348),
 ('tampon', 0.8392389416694641),
 ('nipples', 0.8369837999343872),
 ('arm', 0.8346453905105591)]

## Modeling

### Naive Bayes

#### basic bag of words

In [15]:
nb(X_train_vec, X_val_vec, y_train, y_val)

Accuracy: 0.8086

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.77      0.80       611
           1       0.79      0.84      0.81       601

    accuracy                           0.81      1212
   macro avg       0.81      0.81      0.81      1212
weighted avg       0.81      0.81      0.81      1212


Confusion Matrix:
[[473 138]
 [ 94 507]]


#### 1 hot vector bag of words

In [16]:
nb(X_train_hot, X_val_hot, y_train, y_val)

Accuracy: 0.8086

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.77      0.80       611
           1       0.78      0.85      0.81       601

    accuracy                           0.81      1212
   macro avg       0.81      0.81      0.81      1212
weighted avg       0.81      0.81      0.81      1212


Confusion Matrix:
[[471 140]
 [ 92 509]]


#### TF-IDF

In [17]:
nb(X_train_vec_tf, X_val_vec_tf, y_train, y_val)

Accuracy: 0.8061

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.76      0.80       611
           1       0.78      0.86      0.81       601

    accuracy                           0.81      1212
   macro avg       0.81      0.81      0.81      1212
weighted avg       0.81      0.81      0.81      1212


Confusion Matrix:
[[462 149]
 [ 86 515]]


#### Ngrams (Bi gram)

In [18]:
nb(X_train_vec_bi, X_val_vec_bi, y_train, y_val)


Accuracy: 0.5041

Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       611
           1       0.00      0.00      0.00       601

    accuracy                           0.50      1212
   macro avg       0.25      0.50      0.34      1212
weighted avg       0.25      0.50      0.34      1212


Confusion Matrix:
[[611   0]
 [601   0]]


/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

### Support Vector Machine

#### basic bag of words

In [19]:
support_vector_machine(X_train_vec, X_val_vec, y_train, y_val)

Best Parameters: {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
Best Cross-Validation Accuracy: 0.7859365491771537
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.88      0.84       611
           1       0.87      0.79      0.83       601

    accuracy                           0.84      1212
   macro avg       0.84      0.84      0.84      1212
weighted avg       0.84      0.84      0.84      1212

Accuracy: 0.8358085808580858


#### 1 hot vector bag of words

In [20]:
support_vector_machine(X_train_hot, X_val_hot, y_train, y_val)

Best Parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'sigmoid'}
Best Cross-Validation Accuracy: 0.7872900599052175
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.89      0.84       611
           1       0.87      0.78      0.82       601

    accuracy                           0.83      1212
   macro avg       0.84      0.83      0.83      1212
weighted avg       0.84      0.83      0.83      1212

Accuracy: 0.8325082508250825


#### TF-IDF

In [21]:
support_vector_machine(X_train_vec_tf, X_val_vec_tf, y_train, y_val)

Best Parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'sigmoid'}
Best Cross-Validation Accuracy: 0.7978915220223686
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.89      0.87       611
           1       0.88      0.84      0.86       601

    accuracy                           0.86      1212
   macro avg       0.86      0.86      0.86      1212
weighted avg       0.86      0.86      0.86      1212

Accuracy: 0.8613861386138614


#### Ngrams (Bi gram)

In [22]:
support_vector_machine(X_train_vec_bi, X_val_vec_bi, y_train, y_val)

Best Parameters: {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
Best Cross-Validation Accuracy: 0.5045116176443469
Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       611
           1       0.00      0.00      0.00       601

    accuracy                           0.50      1212
   macro avg       0.25      0.50      0.34      1212
weighted avg       0.25      0.50      0.34      1212

Accuracy: 0.5041254125412541


/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/santiagoromero/Documents/nlp/nlp-env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

### Random Forest

#### basic bag of words

In [14]:
random_forest(X_train_vec, X_val_vec, y_train, y_val)

Fitting 5 folds for each of 81 candidates, totalling 405 fits


(RandomForestClassifier(min_samples_leaf=2, n_estimators=200, random_state=42),
 {'max_depth': None,
  'min_samples_leaf': 2,
  'min_samples_split': 2,
  'n_estimators': 200},
 0.8028052805280528)

#### 1 hot vector bag of words

random_forest(X_train_hot, X_val_hot, y_train, y_val)

#### TF-IDF

In [ ]:
random_forest(X_train_vec_tf, X_val_vec_tf, y_train, y_val)

#### Ngrams (Bi gram)

In [ ]:
random_forest(X_train_vec_bi, X_val_vec_bi, y_train, y_val)